name: game_of_trees
description: Node Based Connection Game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  a_star_algorithm: ^0.0.5
  cupertino_icons: ^1.0.2
  flame: 1.0.0-releasecandidate.15
  flame_forge2d: 0.8.0-releasecandidate.13
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  graphs: ^2.1.0
  directed_graph: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
